== Cluster Access by Cluster Manager, Create Namespace and Role Binding

In this lab we will cover cluster access by cluster manager, create namespaces and role binding for accessing the namespaces.

== Cluster Access

. In the newly created cluster or existing cluster, log in as the cluster manager (or admin in case of existing cluster). The steps are the same irrespective of the role. 

----
pks login -a https://api.pks.pcf4labs.com -u parag -k

Password: ********
API Endpoint: https://api.pks.pcf4labs.com
User: parag
----

. Now we will run the get-credentials command so that this user can get the credentials to access the cluster. The credentials and cluster info comes as a config file that is created or appended by the get-credentials command.

----
pks get-credentials workshop-cluster

Fetching credentials for cluster workshop-cluster.
Password: ********
Context set for cluster workshop-cluster.

You can now switch between clusters by using:
$kubectl config use-context <cluster-name>
----

== Create custom developer group, k8s namespaces and role binding

Now that the cluster manager (or admin) has PKS cluster access, for the purpose of this workshop, we will create a UAA group. This will simulate group of developers that can access this cluster. In reality, there would be either LDAP, SAML or SSO integration in place that will be mapped to UAA group.

----
uaac group add workshop-cluster-namespace01

  id: 28251fb1-9289-4889-9f2f-bd2a0b6dec52
  meta
    version: 0
    created: 2019-06-03T21:24:12.000Z
    lastmodified: 2019-06-03T21:24:12.000Z
  members: 
  schemas: urn:scim:schemas:core:1.0
  displayname: workshop-cluster-namespace01
  zoneid: uaa
----
