kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ns-admins
  namespace: namespace01
subjects:
  - kind: User
    name: dev1
roleRef:
  kind: Role
  name: ns-admin
  apiGroup: rbac.authorization.k8s.io

